import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD.
See the source repository for the original TypeScript.
*/
`;

const production = process.argv[2] === 'production';
const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	jsx: 'automatic',
	// React reads the first to choose its production build, and a library it
	// stands on reads the second, which a CommonJS bundle has no `import.meta`
	// to answer for. Both are said here, where the choice is made.
	define: {
		'process.env.NODE_ENV': JSON.stringify(production ? 'production' : 'development'),
		'import.meta.env': JSON.stringify({ MODE: production ? 'production' : 'development' }),
	},
	logLevel: 'info',
	sourcemap: production ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: production,
});

if (production) {
	await context.rebuild();
	await context.dispose();
} else {
	await context.watch();
}
